const SpareParts = [
    {
        id: "0R58sE2wj8guYrsRP8Xp",
        code: "YDK-765-93923-401",
        definition: "Diğer",
        explanation: "Main Chassis Siyah Bant",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Insulator Batt Comp",
        test: "",
        viCode: "",
    }, {
        id: "GF8QvmdmJXQXxPqLbmoG",
        code: "SUB0001144",
        definition: "Diğer",
        explanation: "Asmdoor, Asm Door Kapağı",
        model: "Plum 360",
        isAvailable: "true",
        name: "Door Cover And Screw",
        test: "true",
        viCode: "122",
    }, {
        id: "0UvaAZlC1Uhdzc2dCane",
        code: "YDK-810-95242-027",
        definition: "Kartlar",
        explanation: "Güç Kartı, Elektrik",
        model: "Plum A",
        isAvailable: "true",
        name: "Power Pwa",
        test: "",
        viCode: "",
    }, {
        id: "0XfkgmqHn4oblMRMuRgp",
        code: "YDK-712-94104-401",
        definition: "Diğer",
        explanation: "Peripheral Parçaları",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Cover Usb Ce3.0",
        test: "",
        viCode: "",
    }, {
        id: "0dcnulvR1HhBuBPs5Mnu",
        code: "YDK-720-10068-001",
        definition: "Vidalar",
        explanation: "Arka Kapak Uzun Vida",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Screw 6-32, X3, 1/4, Pan Head",
        test: "",
        viCode: "",
    }, {
        id: "1AazgZfw5fhI3Z1IU2U0",
        code: "YDK-830-95044-515",
        definition: "Mekanizma",
        explanation: "Hava Sensörü Kartı",
        model: "Ortak",
        isAvailable: "true",
        name: "App Pwa",
        test: "",
        viCode: "",
    }, {
        id: "1LFasIUDE91vOBX3OTNz",
        code: "YDK-735-10861-002",
        definition: "Etiketler",
        explanation: "İngilizce Yan Etiket",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Ops Instr Lbl Ie",
        test: "true",
        viCode: "122",
    }, {
        id: "1daOSV7MiFkeaqb0ne4Q",
        code: "YDK-840-95012-016",
        definition: "Diğer",
        explanation: "Sıvı Kalkanı",
        model: "Plum A",
        isAvailable: "true",
        name: "Shield",
        test: "true",
        viCode: "122",
    }, {
        id: "37CC99gO87b6rkEcQexY",
        code: "YDK-717-95011-402",
        definition: "Mekanizma",
        explanation: "Mekanizma Demiri",
        model: "Ortak",
        isAvailable: "false",
        name: "Pri/sec Valve Leaf Spring",
        test: "",
        viCode: "",
    }, {
        id: "39BQmmNQEfZjAXVqQrwr",
        code: "YDK-810-95006-013",
        definition: "Kartlar",
        explanation: "Peripheral Kartı",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Peripheral Pwa",
        test: "",
        viCode: "",
    }, {
        id: "3FvnmsvmNIHwacXa1jkK",
        code: "YDK-714-00670-403",
        definition: "Diğer",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Shoe I/o Rocker",
        test: "",
        viCode: "",
    }, {
        id: "3Hiql63KDF2M8AoCAZCF",
        code: "YDK-735-97275-401",
        definition: "Etiketler",
        explanation: "Ab Etiketi",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Lbl Set Tubing Guide Labels",
        test: "",
        viCode: "",
    }, {
        id: "3hH0BlR7eHEZOz8hWK6z",
        code: "YDK-712-00654-402",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "false",
        name: "Sft Opener Regulator",
        test: "",
        viCode: "",
    }, {
        id: "3lxQ1BGpAKccVxkiZAkF",
        code: "YDK-841-12388-001",
        definition: "Mekanizma",
        explanation: "Kaset Kapağı Asmdoor",
        model: "Plum A",
        isAvailable: "true",
        name: "Asm Door",
        test: "true",
        viCode: "122",
    }, {
        id: "3rScLCTJXIhpJd4AwrLI",
        code: "YDK-840-95015-017",
        definition: "Diğer",
        explanation: "Türkçe Tuş Takımı",
        model: "Plum A",
        isAvailable: "true",
        name: "Keypad Tr",
        test: "true",
        viCode: "122",
    }, {
        id: "3xaklqk72gIRV7N8oBGj",
        code: "YDK-735-98155-401",
        definition: "Etiketler",
        explanation: "Power Kablo Etiketi",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Lbl Power Cord",
        test: "",
        viCode: "",
    }, {
        id: "43htxqWPQt2zv6Et5bNo",
        code: "YDK-712-95110-402",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Nest Coupler",
        test: "",
        viCode: "",
    }, {
        id: "45vKjFOWM0jP66mlWQIX",
        code: "YDK-810-94108-401",
        definition: "Kartlar",
        explanation: "Anten",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Pwa Antenna Plum Ce3.0, Sngl Ch",
        test: "",
        viCode: "",
    }, {
        id: "4oZH5wmEIQ5EIAuX4M2V",
        code: "YDK-712-94070-402",
        definition: "Diğer",
        explanation: "Pole Clamp Kasa Parçaları, Beyaz",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Bracket Pole Clamp",
        test: "",
        viCode: "",
    }, {
        id: "4sbt9PvV1Zl1uNchHgSW",
        code: "YDK-720-10068-404",
        definition: "Vidalar",
        explanation: "Plum 360 Arka Kapak Uzun Vida",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Screw, 6-32, X2, 1/2, Pan Head, Phılıps",
        test: "",
        viCode: "",
    }, {
        id: "5P3IBzfsrCuUhDPO3b9y",
        code: "YDK-712-00703-006",
        definition: "Diğer",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Bshg Mot",
        test: "",
        viCode: "",
    }, {
        id: "5VHhW9zeQFCGg1fktqJ5",
        code: "YDK-712-94860-405",
        definition: "Kasalar",
        explanation: "İç Kasa",
        model: "Plum 360",
        isAvailable: "true",
        name: "Main Chasis",
        test: "true",
        viCode: "",
    }, {
        id: "5qO0L4SOkZOdFrinSgyS",
        code: "YDK-716-95153-403",
        definition: "Diğer",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Pad Dampening Rear Plate",
        test: "",
        viCode: "",
    }, {
        id: "61EgpzSGVAAYSMRm8RVE",
        code: "YDK-810-95242-531",
        definition: "Kartlar",
        explanation: "Güç Kartı, Elektrik",
        model: "Plum 360",
        isAvailable: "true",
        name: "Power Pwa",
        test: "",
        viCode: "",
    }, {
        id: "64hYtyG36pphExoPu2ZC",
        code: "YDK-804",
        definition: "Kablolar",
        explanation: "Power Kablo",
        model: "Ortak",
        isAvailable: "true",
        name: "Power Cable",
        test: "",
        viCode: "",
    }, {
        id: "6KnShFK9Qen78r0VXOtf",
        code: "YDK-712-95040-401",
        definition: "Diğer",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Lever Door",
        test: "",
        viCode: "",
    }, {
        id: "6LvMS1ji7io8UWBdYMds",
        code: "YDK-765-11388-001",
        definition: "Diğer",
        explanation: "Gasket",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Enclosure Gasket",
        test: "",
        viCode: "",
    }, {
        id: "78myOycALSvvywAqSqHG",
        code: "YDK-710-10621-401",
        definition: "Diğer",
        explanation: "Ses Açma Plastiği",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Knob Gray 1/8",
        test: "true",
        viCode: "141",
    }, {
        id: "7AoOFrrb4J51CiCsBIL9",
        code: "YDK-SUB0000864",
        definition: "Diğer",
        explanation: "Batarya",
        model: "Ortak",
        isAvailable: "true",
        name: "Battery",
        test: "",
        viCode: "",
    }, {
        id: "7HtDCaNoZC2BIHu7Dgam",
        code: "YDK-721-14171-402",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Washer Cprsn .121ıd .045thk Stl",
        test: "",
        viCode: "",
    }, {
        id: "7IOeID8Ixm6cR7Ym8x4z",
        code: "YDK-725-72283-402",
        definition: "Diğer",
        explanation: "Beyaz Klips Tutacağı",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Ca Tie Plastic Adh Back Rw",
        test: "",
        viCode: "",
    }, {
        id: "7NVFNCQ8btxBd0TLFig5",
        code: "YDK-712-00655-002",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Rocker Regulator Opener",
        test: "",
        viCode: "",
    }, {
        id: "7gFNpwLI6Cm70KYRxL8K",
        code: "YDK-721-14138-002",
        definition: "Diğer",
        explanation: "Peripheral Parçası",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Washer Shldr #4 Nylon",
        test: "",
        viCode: "",
    }, {
        id: "7u1XDMq1jDMpP09eD6va",
        code: "YDK-718-15007-402",
        definition: "Diğer",
        explanation: "Siyah Plastik",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Rivet Push Plastic",
        test: "",
        viCode: "",
    }, {
        id: "7x0SfFqLEkxHPMrCzX8s",
        code: "YDK-735-98159-403",
        definition: "Etiketler",
        explanation: "Peripheral Etiketi",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Product Rating Label (turkey",
        test: "",
        viCode: "",
    }, {
        id: "8TwOzARPVsGJxK5cH5N2",
        code: "YDK-MEC0000925",
        definition: "Kasalar",
        explanation: "Ön Kasa Front Case",
        model: "Plum 360",
        isAvailable: "true",
        name: "Housing Front",
        test: "true",
        viCode: "122",
    }, {
        id: "8pC8O2tHWSDeHq38kBgj",
        code: "YDK-712-95067-401",
        definition: "Mekanizma",
        explanation: "Turuncu Parça",
        model: "Ortak",
        isAvailable: "true",
        name: "Pivot",
        test: "",
        viCode: "",
    }, {
        id: "8y3TmqbfY8VYEpb8VNV0",
        code: "YDK-810-97400-506",
        definition: "Kartlar",
        explanation: "Peripheral Kartı",
        model: "Plum 360",
        isAvailable: "true",
        name: "Peripheral Pwa",
        test: "",
        viCode: "",
    }, {
        id: "97q5kEPXL1SNxLsCkZzi",
        code: "YDK-712-94861-402",
        definition: "Diğer",
        explanation: "Arka Kapak Mor Parça",
        model: "Plum 360",
        isAvailable: "true",
        name: "Bracket Handle",
        test: "true",
        viCode: "141",
    }, {
        id: "9oVYARTo5N9x9oNUHsGz",
        code: "YDK-718-97671-401",
        definition: "Vidalar",
        explanation: "Peripheral Parçası",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Rivet 125 Christmas Tree Black",
        test: "",
        viCode: "",
    }, {
        id: "9tQxcnauQCaVVoYhns7F",
        code: "YDK-840-95106-404",
        definition: "Mekanizma",
        explanation: "Arka Motor",
        model: "Ortak",
        isAvailable: "true",
        name: "Plunger Motor",
        test: "",
        viCode: "",
    }, {
        id: "A9xMb0lFROWA3LD11kyv",
        code: "YDK-721-13112-401",
        definition: "Mekanizma",
        explanation: "Handle Door Parçası",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Ring Rtng .188 X.025 Sst",
        test: "false",
        viCode: "",
    }, {
        id: "AABAmL1rQbBAGpJz6al4",
        code: "YDK-826-95059-402",
        definition: "Kablolar",
        explanation: "Cpu Mechanism Gri Kablo",
        model: "Ortak",
        isAvailable: "true",
        name: "Cpu Driver Cable",
        test: "",
        viCode: "",
    }, {
        id: "AFfxa3XxwjKFPKANZUmW",
        code: "YDK-729-38320-001",
        definition: "Mekanizma",
        explanation: "Bant",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Tape Ins 3m 1350 2mil Wht 1.5",
        test: "",
        viCode: "",
    }, {
        id: "AyF589dQD35AdAFnuQS2",
        code: "YDK-830-95102-001",
        definition: "Mekanizma",
        explanation: "Alt Motor",
        model: "Ortak",
        isAvailable: "true",
        name: "I/o Motor",
        test: "",
        viCode: "",
    }, {
        id: "BMuazdssVkbtI2BeqxPU",
        code: "YDK-735-10930-001",
        definition: "Etiketler",
        explanation: "Türkçe Yan Labels",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Lbl Set Ops/alarms V11 Turkey",
        test: "true",
        viCode: "122",
    }, {
        id: "BcjebGSeopIV4k8JtBvX",
        code: "YDK-735-97264-001",
        definition: "Etiketler",
        explanation: "Volume Etiketi Sol+",
        model: "Plum A",
        isAvailable: "false",
        name: "Lbl High-low English",
        test: "",
        viCode: "",
    }, {
        id: "BhAhCWQhP8TGhmGS2QA8",
        code: "YDK-715-95027-001",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Pin Prox/distal Pressure Sensor",
        test: "",
        viCode: "",
    }, {
        id: "BmMFQsEuVRub0qVOy5KV",
        code: "YDK-710-10621-403",
        definition: "Diğer",
        explanation: "Plum 360 Ses Açma Plastiği Kapağı",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Knob Cap Gray",
        test: "false",
        viCode: "",
    }, {
        id: "BxlGijIlygGSo40me706",
        code: "YDK-720-10066-402",
        definition: "Vidalar",
        explanation: "Retainer Cord Vidası?",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Screw 6-32, 5/8, Pan Head Philips With Washer",
        test: "",
        viCode: "",
    }, {
        id: "CQtT6fRrbwS0WRuT8P9M",
        code: "YDK-712-94869-402",
        definition: "Kasalar",
        explanation: "Peripheral Kasası",
        model: "Plum 360",
        isAvailable: "true",
        name: "Cover Peripheral",
        test: "true",
        viCode: "141",
    }, {
        id: "CviiY7vpFwF1uGz7ht7A",
        code: "YDK-810-95006-011",
        definition: "Kartlar",
        explanation: "Peripheral Kartı",
        model: "Plum A",
        isAvailable: "true",
        name: "Peripheral Pwa",
        test: "",
        viCode: "",
    }, {
        id: "D0O0gdTTpVSQ29cOTPqz",
        code: "YDK-712-95090-006",
        definition: "Kasalar",
        explanation: "Peripheral Kasası",
        model: "Plum A",
        isAvailable: "true",
        name: "Cover Peripheral",
        test: "true",
        viCode: "141",
    }, {
        id: "D1PkNoVu3LeqCy6gLmO1",
        code: "YDK-683-67000-401",
        definition: "Kablolar",
        explanation: "Switch Pwa Kablosu Beyaz",
        model: "Ortak",
        isAvailable: "true",
        name: "Cable Flat 8 Cond",
        test: "",
        viCode: "",
    }, {
        id: "DClKE8cvYIIUaxtTuU3d",
        code: "YDK-715-95195-402",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Pin Fixed Cassette Locator",
        test: "",
        viCode: "",
    }, {
        id: "DZhXZIHN5uq1pM5chvv3",
        code: "YDK-830-03329-506",
        definition: "Diğer",
        explanation: "Hoparlör",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Piezo Alarm",
        test: "",
        viCode: "",
    }, {
        id: "DyoEPExY2wceBHdGsttc",
        code: "YDK-712-94855-403",
        definition: "Kasalar",
        explanation: "Batarya Kapağı",
        model: "Plum 360",
        isAvailable: "true",
        name: "Battery Door",
        test: "true",
        viCode: "",
    }, {
        id: "E2ZZx17ged6a4T9P9mgN",
        code: "YDK-720-10323-402",
        definition: "Vidalar",
        explanation: "Pivot Vidası",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Screw 4-40, 1/4, Hex Head Sltd W/washer",
        test: "",
        viCode: "",
    }, {
        id: "F2C0QNrkgXFsTiWG4QmH",
        code: "YDK-711-10619-001",
        definition: "Diğer",
        explanation: "Peripheral Parçaları Siyah",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Cap Vinyl 1/2 Long Blk",
        test: "",
        viCode: "",
    }, {
        id: "F5asx9T0kyWjAhj0Jd2z",
        code: "YDK-678-72366-401",
        definition: "Vidalar",
        explanation: "Topraklama Vidası",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Term Equipotential",
        test: "",
        viCode: "",
    }, {
        id: "F8lfJWafWpPm5JYvRwdQ",
        code: "YDK-712-00554-406",
        definition: "Mekanizma",
        explanation: "Alttaki Valf Pinleri",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Valve Pins I/o Valve",
        test: "",
        viCode: "",
    }, {
        id: "FWLIprRNJGYDm0nwZEkW",
        code: "YDK-692-95036-514",
        definition: "Kartlar",
        explanation: "Ekran Display",
        model: "Plum 360",
        isAvailable: "true",
        name: "Display",
        test: "true",
        viCode: "122",
    }, {
        id: "IOzDubd88Nds91Y0XAJX",
        code: "YDK-692-95036-803",
        definition: "Kartlar",
        explanation: "Ekran Display",
        model: "Plum A",
        isAvailable: "true",
        name: "Display",
        test: "true",
        viCode: "122",
    }, {
        id: "Gb49Vc1TWEloMjJXnV4O",
        code: "YDK-712-95087-010",
        definition: "Kasalar",
        explanation: "Arka Kasa",
        model: "Plum A",
        isAvailable: "true",
        name: "Rear Case",
        test: "true",
        viCode: "141",
    }, {
        id: "GhK0TOpKf3zfrHLf0Oz8",
        code: "YDK-830-95101-001",
        definition: "Mekanizma",
        explanation: "Sol Motor",
        model: "Ortak",
        isAvailable: "true",
        name: "L/s Motor",
        test: "",
        viCode: "",
    }, {
        id: "HGqlQFrQEJ4xEWRxUirr",
        code: "YDK-712-95085-009",
        definition: "Kasalar",
        explanation: "İç Kasa",
        model: "Plum A",
        isAvailable: "true",
        name: "Main Chasis",
        test: "true",
        viCode: "",
    }, {
        id: "HUg79xz2q6LO4wZ5TvFb",
        code: "YDK-810-95018-510",
        definition: "Mekanizma",
        explanation: "Arka Kart, Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "true",
        name: "Driver Pwa",
        test: "",
        viCode: "",
    }, {
        id: "Hw2bDesPsSrI5W7dc6ps",
        code: "YDK-735-10864-002",
        definition: "Etiketler",
        explanation: "İngilizce Arka Etiket",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Rear Caution Lbl Ie",
        test: "",
        viCode: "",
    }, {
        id: "I4DTlbhSdAItdHaalcol",
        code: "YDK-712-95111-003",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Shaft Ext Coupler",
        test: "",
        viCode: "",
    }, {
        id: "IVOayiQ3lmyYpaDVPmcA",
        code: "YDK-735-97265-002",
        definition: "Etiketler",
        explanation: "Ses Etiketi Sağ+",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Lbl Low-high Turkish",
        test: "false",
        viCode: "",
    }, {
        id: "Irl0xhQboPXSGFiVPxEm",
        code: "YDK-714-94076-401",
        definition: "Diğer",
        explanation: "Pole Clamp Parçası Siyah",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Bracket Handle ????",
        test: "",
        viCode: "",
    }, {
        id: "J9LAvitFMAX08n55zvcj",
        code: "YDK-735-95228-002",
        definition: "Etiketler",
        explanation: "11971-36 İngilizce Peripheral Etiketi",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Switch Port Label",
        test: "false",
        viCode: "",
    }, {
        id: "JDe7XrZbxrgWVbGfknwJ",
        code: "YDK-712-00671-403",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Rocker Sec Valve",
        test: "",
        viCode: "",
    }, {
        id: "JUEgrtNYIqxtBMq7opok",
        code: "YDK-712-00658-003",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Cam Stac, Pri",
        test: "",
        viCode: "",
    }, {
        id: "JXREmbHJygxRtxjDae5l",
        code: "YDK-710-10621-403",
        definition: "Diğer",
        explanation: "Plum 360 Ses Açma Plastiği Kapağı",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Knob Cap Gray",
        test: "false",
        viCode: "",
    }, {
        id: "JsPKTE4Qj9vkyvSf4uoq",
        code: "YDK-765-94870-402",
        definition: "Diğer",
        explanation: "Hoparlör Koruyucusu",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Splashguard",
        test: "",
        viCode: "",
    }, {
        id: "K4aG3OUubd5SGGB1cWCD",
        code: "YDK-712-00673-403",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Rkr Outlet Valve",
        test: "",
        viCode: "",
    }, {
        id: "KB8uiQpOqCodrABzlY6t",
        code: "YDK-720-10211-402",
        definition: "Vidalar",
        explanation: "Peripheral Vidası",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Screw 4-40, 5/8, Pan Head Philips",
        test: "",
        viCode: "",
    }, {
        id: "KJdAOnzpxqkPOBoGynvJ",
        code: "YDK-712-95100-404",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Plum A",
        isAvailable: "false",
        name: "Pl Rear Mech",
        test: "",
        viCode: "",
    }, {
        id: "KSrP6fCcvQ0s46sKXe1a",
        code: "YDK-855-95715-015",
        definition: "Mekanizma",
        explanation: "Plum 360 Mekanizma",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Mechanism Plum 360",
        test: "",
        viCode: "",
    }, {
        id: "KZwiGNBnE8T3yal5VoF8",
        code: "YDK-820-95542-003",
        definition: "Diğer",
        explanation: "Pole Clamp Demiri",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Base W/rubber",
        test: "",
        viCode: "",
    }, {
        id: "Kd4nIcgnFQ4ag5LTS6Dt",
        code: "YDK-712-95030-001",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Spcr Pressure Sensor",
        test: "",
        viCode: "",
    }, {
        id: "KrKEuP0gOzd2af0Z1SeN",
        code: "YDK-735-95133-005",
        definition: "Etiketler",
        explanation: "Plum A Etiketi",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Label Logo",
        test: "",
        viCode: "",
    }, {
        id: "KyjYT8B8QgtgOtOaM5JR",
        code: "YDK-840-94075-402",
        definition: "Diğer",
        explanation: "Sıkma Kolu",
        model: "Plum 360",
        isAvailable: "true",
        name: "Pole Clamp Knob",
        test: "true",
        viCode: "141",
    }, {
        id: "LOioNz9y49oIPsfB0qPw",
        code: "YDK-710-10621-402",
        definition: "Diğer",
        explanation: "Plum 360 Ses Açma Plastiği Altı",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Knob Cover Gray",
        test: "",
        viCode: "",
    }, {
        id: "La8gPmTQFkm4Rd7JOak3",
        code: "YDK-735-10934-002",
        definition: "Etiketler",
        explanation: "Türkçe Arka Etiket",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Lbl Rear Caution Turkey",
        test: "",
        viCode: "",
    }, {
        id: "LdL5reNX60xzg8ZzvWMx",
        code: "YDK-710-10621-003",
        definition: "Diğer",
        explanation: "Plum A Ses Açma Plastiği Kapağı",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Knob Cap Gray",
        test: "",
        viCode: "",
    }, {
        id: "MB3pTCC4wCDsiohDej3S",
        code: "YDK-840-97669-401",
        definition: "Diğer",
        explanation: "Tuş Takımı",
        model: "Plum 360",
        isAvailable: "true",
        name: "Keypad",
        test: "true",
        viCode: "122",
    }, {
        id: "MODV2Ys99MclstIfcnWz",
        code: "YDK-720-10233-407",
        definition: "Vidalar",
        explanation: "Peripheral Vidası",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Screw 4-40, 3/8, Button Head Ss",
        test: "",
        viCode: "",
    }, {
        id: "MZrleYkWjVxDDZ1degbv",
        code: "YDK-820-95251-403",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Asm Coupler Body/lead Screw",
        test: "",
        viCode: "",
    }, {
        id: "N8LJuq69jx3gWc2qPIxF",
        code: "YDK-712-95065-006",
        definition: "Diğer",
        explanation: "Power Kablo Tutucu Retainer Cord",
        model: "Plum A",
        isAvailable: "true",
        name: "Retainer Cord",
        test: "true",
        viCode: "141",
    }, {
        id: "NY3yw2kEJR1217se369X",
        code: "YDK-722-10257-001",
        definition: "Diğer",
        explanation: "Peripheral Parçası",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Nut 1/4 Hex",
        test: "",
        viCode: "",
    }, {
        id: "NnXJMrqrYTaJt8IgCjXX",
        code: "YDK-712-95033-001",
        definition: "Diğer",
        explanation: "?",
        model: "Ortak",
        isAvailable: "undefined",
        name: "O-ring Pressure Sensor",
        test: "",
        viCode: "",
    }, {
        id: "NrIdoGBwZz9A1NtfUJc2",
        code: "YDK-710-10621-002",
        definition: "Diğer",
        explanation: "Plum A Ses Açma Plastiği Altı",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Knob Cover Gray",
        test: "false",
        viCode: "",
    }, {
        id: "ODc9YbShj7Li8v2lrETk",
        code: "YDK-712-97667-401",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "true",
        name: "Link Door",
        test: "",
        viCode: "",
    }, {
        id: "OXjSsKs9UaWq26oH52x8",
        code: "YDK-765-95081-001",
        definition: "Gasket",
        explanation: "Gasket",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Gskt Handle",
        test: "",
        viCode: "",
    }, {
        id: "PcCJ23PhvklmpTrUogMf",
        code: "YDK-712-94866-402",
        definition: "Diğer",
        explanation: "Peripheral Parçaları",
        model: "Plum 360",
        isAvailable: "true",
        name: "Cover Antennal Lcm Ce 3.0",
        test: "true",
        viCode: "141",
    }, {
        id: "PhrRKXP3sRsOC9C0OTUl",
        code: "YDK-683-67000-403",
        definition: "Kablolar",
        explanation: "Cpu, Beyaz Kablo",
        model: "Ortak",
        isAvailable: "true",
        name: "Cable Flex 14 Conductor",
        test: "",
        viCode: "",
    }, {
        id: "Q6vCW75GAHx7SmdEkXCe",
        code: "YDK-735-10865-001",
        definition: "Etiketler",
        explanation: "12391-36 İngilizce Peripheral Etiketi",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Switch/port Lbl Ie",
        test: "false",
        viCode: "141",
    }, {
        id: "QBUjEnoJ8Y5bC3PVvt0o",
        code: "YDK-714-95203-402",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Bracket Rear Plate Left",
        test: "",
        viCode: "",
    }, {
        id: "QTejiSpMkFfIvQD9pih4",
        code: "YDK-810-97401-503",
        definition: "Kartlar",
        explanation: "Peripheral Parçası",
        model: "Plum 360",
        isAvailable: "true",
        name: "Bom Pwa Common A+ Ce3",
        test: "",
        viCode: "",
    }, {
        id: "QXOiMgawTvbQU0Bw8jpC",
        code: "YDK-721-13113-401",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Ring Rtng .312 X.025 Sst",
        test: "",
        viCode: "",
    }, {
        id: "ROp6G1NSJ7Vomr5yYYhE",
        code: "YDK-717-00684-404",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Spring Outlet Valve Leaf (cclt",
        test: "",
        viCode: "",
    }, {
        id: "RQ0Ts4IdSSXqCkFSSd4a",
        code: "YDK-765-94106-401",
        definition: "Diğer",
        explanation: "Peripheral Kartı Koruyucu",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Insulator Lcm Ce3.0",
        test: "",
        viCode: "",
    }, {
        id: "RkoIFXUcr7T3PP1srUb5",
        code: "YDK-720-98348-401",
        definition: "Vidalar",
        explanation: "Ön Kapak Mor Parça Vidası",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Screw 4-20 1/4 Pan Head Philips",
        test: "",
        viCode: "",
    }, {
        id: "Rl4wrkZjbxP7ve5MKEDh",
        code: "YDK-717-94872-401",
        definition: "Diğer",
        explanation: "Peripheral Parçası",
        model: "Plum 360",
        isAvailable: "false",
        name: "Emi Spring Lcm Ce3.0, Upper",
        test: "",
        viCode: "",
    }, {
        id: "RvvFtYySsXmOuG44oTnO",
        code: "YDK-717-95017-003",
        definition: "Mekanizma",
        explanation: "Asmdoor Demiri",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Spring Cassette Guide",
        test: "",
        viCode: "",
    }, {
        id: "SCgKBTksBSlvCltyvXLn",
        code: "YDK-765-93926-401",
        definition: "Gasket",
        explanation: "Ön Kasa Gasketi",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Gskt Display Seal (cclt",
        test: "",
        viCode: "",
    }, {
        id: "SI7yrlSi32vC45WOw3gM",
        code: "YDK-715-95032-001",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Retainer Pressure Sensor ??",
        test: "",
        viCode: "",
    }, {
        id: "SgSNXusGYIZEzmGWWf0a",
        code: "YDK-720-10325-404",
        definition: "Vidalar",
        explanation: "Batarya Kapağı Vidası",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Screw 6-32, 3/8, Hex Head Slotted W/washer",
        test: "",
        viCode: "",
    }, {
        id: "SmPUlCrqD50AuzRdcWC6",
        code: "YDK-810-95022-404",
        definition: "Mekanizma",
        explanation: "Yan Kart",
        model: "Ortak",
        isAvailable: "true",
        name: "Switch Pwa",
        test: "",
        viCode: "",
    }, {
        id: "SxjUd2T2Qt1ozQiV41YA",
        code: "YDK-712-00547-405",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Valve Pin P/s Valve",
        test: "",
        viCode: "",
    }, {
        id: "T7pOKVIEajqBBnEhrn4L",
        code: "YDK-855-95004-010",
        definition: "Mekanizma",
        explanation: "Mekanizma",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Mechanism",
        test: "",
        viCode: "",
    }, {
        id: "TLtbYSd5Le5c7YEQgcIe",
        code: "YDK-714-95166-402",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Plate Dampening Rear",
        test: "",
        viCode: "",
    }, {
        id: "TZltzTqODkrLm9ivHKyd",
        code: "YDK-714-95202-402",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Bracket Rear Plate Right",
        test: "",
        viCode: "",
    }, {
        id: "TofYPNYxr5N0orYLXlPy",
        code: "YDK-710-10621-001",
        definition: "Diğer",
        explanation: "Plum A Ses Açma Plastiği",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Knob Gray 1/8",
        test: "",
        viCode: "",
    }, {
        id: "UJd8nQlWLt8mmSWCKu2t",
        code: "YDK-735-98158-401",
        definition: "Etiketler",
        explanation: "Pembe Etiket",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Lbl Close Clamps",
        test: "",
        viCode: "",
    }, {
        id: "UTUstZO9w3BaENZH9ckY",
        code: "YDK-710-10621-402",
        definition: "Diğer",
        explanation: "Plum 360 Ses Açma Plastiği Altı",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Knob Cover Gray",
        test: "false",
        viCode: "",
    }, {
        id: "UTxju9LI5X1nsMI7GwXp",
        code: "YDK-712-95021-003",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Plate Clmpg Pressure Sensor",
        test: "",
        viCode: "",
    }, {
        id: "UYkRwEfjzKkd5dHZkURO",
        code: "YDK-730-97249-401",
        definition: "Diğer",
        explanation: "Peripheral Parçası Siyah Kauçuk",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Cover Io Lcm Ce3",
        test: "true",
        viCode: "141",
    }, {
        id: "UlqyJxIUhe3b0ch9dyU1",
        code: "YDK-712-95048-401",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Opener Regulator",
        test: "",
        viCode: "",
    }, {
        id: "V3aMUAcHmFbOpYpzqWpg",
        code: "YDK-717-00683-408",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Sprinf Inlet Valveleaf",
        test: "",
        viCode: "",
    }, {
        id: "V6H4Z9ElPsMQGO2REyZy",
        code: "YDK-712-94071-401",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Lever Cover",
        test: "",
        viCode: "",
    }, {
        id: "VG5y38FoIAAlrdMfDa5F",
        code: "YDK-712-95028-001",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Tip Distal Pressure Sensor",
        test: "",
        viCode: "",
    }, {
        id: "VHMJESzbCfDk6cAGSgwu",
        code: "YDK-765-97672-401",
        definition: "Gasket",
        explanation: "Shield Gasket",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Gskt Fluid Shield",
        test: "",
        viCode: "",
    }, {
        id: "W1GL4Ka6I7k8XcXhyIgD",
        code: "YDK-SUB0001145",
        definition: "Diğer",
        explanation: "Door Inner Cover And Screw, Asmdoor",
        model: "Plum 360",
        isAvailable: "true",
        name: "Asm Door",
        test: "true",
        viCode: "122",
    }, {
        id: "WBv8MqWD3uu5X8bdOga9",
        code: "YDK-735-10935-001",
        definition: "Etiketler",
        explanation: "Kolu Kapat Etiketi",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Lbl Close Lever Turkey",
        test: "false",
        viCode: "",
    }, {
        id: "WOo0sm0mqITq9ShPxJRB",
        code: "YDK-840-95115-003",
        definition: "Diğer",
        explanation: "Demirli Sıkma Kolu",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Pole Clamp Assembly",
        test: "",
        viCode: "",
    }, {
        id: "XHIzMYZPZSxyZ6ZQgOkE",
        code: "YDK-735-97265-001",
        definition: "Etiketler",
        explanation: "Volum Etiketi Sağ+",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Lbl Low-high English",
        test: "",
        viCode: "",
    }, {
        id: "XuY9yVwN1HFYqLsICV7K",
        code: "YDK-826-95062-001",
        definition: "Kablolar",
        explanation: "Batarya Kablosu",
        model: "Ortak",
        isAvailable: "true",
        name: "Asm Cable Battery",
        test: "",
        viCode: "",
    }, {
        id: "Y7A5bHFJC5erkTa51qrX",
        code: "YDK-712-00660-402",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Support Pri/sec Valve",
        test: "",
        viCode: "",
    }, {
        id: "YUHbSeAy09FRvZDCZncA",
        code: "YDK-712-95107-402",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Retainer Plunger",
        test: "",
        viCode: "",
    }, {
        id: "YiR6Ew5kjKpMtMZiGAoF",
        code: "YDK-717-95093-001",
        definition: "Diğer",
        explanation: "Askı Demiri Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Rocker Regulator Closer",
        test: "",
        viCode: "",
    }, {
        id: "ZMbQ3yTcqepG6aBWfob7",
        code: "YDK-826-95060-401",
        definition: "Kablolar",
        explanation: "Power Mechanism Kırmızı Kablo",
        model: "Ortak",
        isAvailable: "true",
        name: "Asm Cable Motor Power",
        test: "",
        viCode: "",
    }, {
        id: "a6InAcZW6s0aRevSB70t",
        code: "YDK-712-00681-404",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Sprt Bot Spr",
        test: "",
        viCode: "",
    }, {
        id: "a9sBLQacPGIsnlkDZti0",
        code: "YDK-720-10031-001",
        definition: "Vidalar",
        explanation: "Keypad Ve Asmdoor Vidası",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Screw 4-24 1/4 Phh Pnh Hilo 18-8sst",
        test: "",
        viCode: "",
    }, {
        id: "bQGyed0kebBPi4mLEMas",
        code: "YDK-716-00725-402",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Pad Handle Door Stop",
        test: "",
        viCode: "",
    }, {
        id: "bo3wabstfjyvslZVXo0A",
        code: "YDK-SUB0000558",
        definition: "Diğer",
        explanation: "Ön Kasa Mor Parça",
        model: "Plum 360",
        isAvailable: "true",
        name: "Proximal Tubing Guide",
        test: "true",
        viCode: "122",
    }, {
        id: "btK4e0a2Gt18QDDKaSCO",
        code: "YDK-707-95092-001",
        definition: "Diğer",
        explanation: "Askı Demiri",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Bag Hanger",
        test: "",
        viCode: "",
    }, {
        id: "byFdsZghpfdqD8ukLSBR",
        code: "YDK-810-11820-007",
        definition: "Kartlar",
        explanation: "Peripheral Kartı",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Peripheral Pwa",
        test: "",
        viCode: "",
    }, {
        id: "c23OBZqgt68hMkN8zeD0",
        code: "YDK-EE0000118",
        definition: "Kartlar",
        explanation: "Cpu Kartı",
        model: "Ortak",
        isAvailable: "true",
        name: "Cpu Pwa",
        test: "",
        viCode: "",
    }, {
        id: "ckSqSZDQzR5qatpgVlok",
        code: "YDK-720-10318-001",
        definition: "Vidalar",
        explanation: "?",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Screw 6-32, 3/8, Sltd Hwh Type T D",
        test: "",
        viCode: "",
    }, {
        id: "d0CzUpZ4LvL6WpAxksqF",
        code: "YDK-735-00569-001",
        definition: "Etiketler",
        explanation: "İngilizce Üst Etiket",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Lbl Caution Intl Uk",
        test: "",
        viCode: "",
    }, {
        id: "d36DPD7xJQgx29pkaw2q",
        code: "YDK-720-10181-009",
        definition: "Vidalar",
        explanation: "Arka Kapak Kisa Vida",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Screw Holds Back Case",
        test: "",
        viCode: "",
    }, {
        id: "d3mfCaUwna5P48uVXDCk",
        code: "YDK-729-99155-401",
        definition: "Etiketler",
        explanation: "Peripheral Etiketi",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Serial Number Cover (mac Address",
        test: "",
        viCode: "",
    }, {
        id: "dMa8sMSUP8zdLKv19urq",
        code: "YDK-712-95031-001",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Block Pressure Sensor",
        test: "",
        viCode: "",
    }, {
        id: "dOBvmMysNNFC6W9HDns7",
        code: "YDK-735-10936-001",
        definition: "Etiketler",
        explanation: "Kolu Kapat Etiketi",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Lbl Close Lever W/arrow Ef Trk",
        test: "",
        viCode: "",
    }, {
        id: "djPvPFFjfpDiG6PMG1Um",
        code: "YDK-720-10068-403",
        definition: "Vidalar",
        explanation: "Plum 360 Arka Kapak Kisa Vida",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Screw, 6-32, X2, 1/2, Pan Head, Phılıps",
        test: "",
        viCode: "",
    }, {
        id: "eaQAWbUSqhPnrjH1k3Xr",
        code: "YDK-683-67000-402",
        definition: "Kablolar",
        explanation: "Mekanizma Üstteki Beyaz Kablo",
        model: "Ortak",
        isAvailable: "true",
        name: "Cable Flat 20 Cond",
        test: "",
        viCode: "",
    }, {
        id: "elPprbVzDxmsZAtlColX",
        code: "YDK-720-10062-402",
        definition: "Vidalar",
        explanation: "Retainer Cord Vidası",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Screw Jack 4-40, 7/16",
        test: "",
        viCode: "",
    }, {
        id: "emtB750J9ZUDcWLgWRJs",
        code: "YDK-735-10937-001",
        definition: "Etiketler",
        explanation: "12391-06 Türkçe Peripheral Etiketi",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Switch/port Cbl Turkey",
        test: "",
        viCode: "",
    }, {
        id: "ez2am0TssjkhxWduhPGu",
        code: "YDK-765-94875-401",
        definition: "Gasket",
        explanation: "Gasket",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Gskt Front/rear Enclosure",
        test: "",
        viCode: "",
    }, {
        id: "g7hLqUeNrnzgryyrTApE",
        code: "YDK-745-19076-402",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Brg Thrust",
        test: "",
        viCode: "",
    }, {
        id: "gGGWg0G2dMZCdZe8sCAs",
        code: "YDK-717-23000-403",
        definition: "Mekanizma",
        explanation: "Plunger Küçük Yay Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "true",
        name: "Spring Extension 0.063 Dıa, 0.25 Lg",
        test: "",
        viCode: "",
    }, {
        id: "gljJcEY2xhrUFB6btRfl",
        code: "YDK-820-95443-008",
        definition: "Diğer",
        explanation: "Demirsiz Sıkma Kolu",
        model: "Plum A",
        isAvailable: "true",
        name: "Pole Clamp Knob",
        test: "true",
        viCode: "141",
    }, {
        id: "hDWlRZe0FH7L3KiKL2FS",
        code: "YDK-717-94876-401",
        definition: "Diğer",
        explanation: "Peripheral Parçası",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Emi Spring Lcm Ce3.0, Lower",
        test: "",
        viCode: "",
    }, {
        id: "hSdo9O2r9ZhombauKWvQ",
        code: "YDK-826-95058-402",
        definition: "Kablolar",
        explanation: "Power Batarya Arasındaki Kablo",
        model: "Ortak",
        isAvailable: "true",
        name: "Asm Cable Power Sply/btry",
        test: "",
        viCode: "",
    }, {
        id: "hYWDaiADAmIXXnpaBfbm",
        code: "YDK-721-13116-401",
        definition: "Diğer",
        explanation: "?",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Ring Rtng 0.140 X .015 Sst",
        test: "",
        viCode: "",
    }, {
        id: "hzSgzYxBQVM0YQ5UE0WX",
        code: "YDK-712-95084-004",
        definition: "Kasalar",
        explanation: "Front Case Parçası",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Shoe Front Enclosure",
        test: "",
        viCode: "",
    }, {
        id: "i68XyWC2ez5UhUCzwx4D",
        code: "YDK-840-95015-008",
        definition: "Diğer",
        explanation: "İngilizce Tuş Takımı",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Keypad En",
        test: "true",
        viCode: "122",
    }, {
        id: "i95oZjrSPzjtq3PTTXVS",
        code: "YDK-723-10676-402",
        definition: "Diğer",
        explanation: "Display Parçası",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Spacer Display",
        test: "",
        viCode: "",
    }, {
        id: "iVwTe9Oyp74t7DkhDHMG",
        code: "YDK-765-95541-003",
        definition: "Diğer",
        explanation: "Yalıtım Malzemesi",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Insulator Backing Plate",
        test: "",
        viCode: "",
    }, {
        id: "iWTMdv4czv8RaBcqITVU",
        code: "YDK-712-00672-403",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Rkr Inlet Valve (cc",
        test: "",
        viCode: "",
    }, {
        id: "iWyvZYpx6t2YuOdQ7p8U",
        code: "YDK-712-00659-002",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Cam Stac, I/o",
        test: "",
        viCode: "",
    }, {
        id: "ioRqgZCJRVOfoAkKV0bp",
        code: "YDK-712-95109-001",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Body Coupler",
        test: "",
        viCode: "",
    }, {
        id: "irBV1x65xXJwPztmAslM",
        code: "YDK-765-95154-001",
        definition: "Diğer",
        explanation: "Hoparlör Koruyucusu",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Splash Guard (piezo",
        test: "",
        viCode: "",
    }, {
        id: "ivHrOSyu2Ukkzpee4IGT",
        code: "YDK-735-95131-003",
        definition: "Etiketler",
        explanation: "Batarya Etiketi",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Label Battery 6v",
        test: "",
        viCode: "",
    }, {
        id: "k7iBfeUERZuSZA5BthoW",
        code: "YDK-712-95076-001",
        definition: "Diğer",
        explanation: "Kaset Kolu",
        model: "Plum A",
        isAvailable: "true",
        name: "Handle Door",
        test: "true",
        viCode: "122",
    }, {
        id: "k8LsecJ9gyREuJesi1T2",
        code: "YDK-712-95088-003",
        definition: "Diğer",
        explanation: "Batarya Kapağı",
        model: "Plum A",
        isAvailable: "true",
        name: "Battery Door",
        test: "true",
        viCode: "",
    }, {
        id: "kKqauritHmTThlG84Jmt",
        code: "YDK-712-94858-405",
        definition: "Diğer",
        explanation: "Kaset Kolu",
        model: "Plum 360",
        isAvailable: "true",
        name: "Handle Door",
        test: "true",
        viCode: "122",
    }, {
        id: "kN4v1Ltg4TfUkUGJjoEo",
        code: "YDK-725-72261-401",
        definition: "Diğer",
        explanation: "Klips",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Cable Ties",
        test: "",
        viCode: "",
    }, {
        id: "kg09bwxbqRsKHHmL7I9O",
        code: "YDK-712-95065-407",
        definition: "Diğer",
        explanation: "Power Kablo Tutucu",
        model: "Plum 360",
        isAvailable: "true",
        name: "Retainer Cord",
        test: "true",
        viCode: "141",
    }, {
        id: "khxC59ky2JS5hD4rJIpE",
        code: "YDK-735-98163-401",
        definition: "Etiketler",
        explanation: "Ön Kapak Gri Etiket",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Lbl Follow Instructions For Use",
        test: "",
        viCode: "",
    }, {
        id: "klBPS7dTJpwHnXavIx7Y",
        code: "YDK-720-10214-002",
        definition: "Vidalar",
        explanation: "Peripheral Parçaları",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Screw 4-40, 1/4, Hex Nylon",
        test: "",
        viCode: "",
    }, {
        id: "kxz9Ivta0aOLqVpR0QfB",
        code: "YDK-712-00669-403",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Rocker Pri Valve",
        test: "",
        viCode: "",
    }, {
        id: "l8eLRpgvLPGSAmtDb82E",
        code: "YDK-765-97669-401",
        definition: "Diğer",
        explanation: "Peripheral Parçaları",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Insulator Secondary",
        test: "",
        viCode: "",
    }, {
        id: "lFNPbUrLqIAru84aoH1P",
        code: "YDK-714-95117-001",
        definition: "Diğer",
        explanation: "Pole Clamp Parçası",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Plate Backing Pole Clamp",
        test: "",
        viCode: "",
    }, {
        id: "lYWUK2xjL9NXKRySG0lJ",
        code: "YDK-712-95049-406",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Closer Regulator",
        test: "",
        viCode: "",
    }, {
        id: "ls4aLtSKIkkRHPrHpOE2",
        code: "YDK-721-14181-410",
        definition: "Diğer",
        explanation: "Büyük Pul",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Washer Flat .253 Id .050 Thk",
        test: "",
        viCode: "",
    }, {
        id: "lv4gxzHs8KShah3yzB4A",
        code: "YDK-717-23017-402",
        definition: "Mekanizma",
        explanation: "Plunger Yayı, Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Sprıng, Stk, Extensıon, 0.180 Dıa, Ss",
        test: "",
        viCode: "",
    }, {
        id: "m77iLKBKpl7if99j2WdB",
        code: "YDK-720-10039-001",
        definition: "Vidalar",
        explanation: "Retainer Cord Vidası?",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Screw Lock Conn 4-40",
        test: "",
        viCode: "",
    }, {
        id: "mD6jgwZIqHs87CpxefQ8",
        code: "YDK-722-10260-001",
        definition: "Diğer",
        explanation: "Peripheral Parçası",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Ring Retainer",
        test: "",
        viCode: "",
    }, {
        id: "mRLJ56CJm2THgmoZ3gAT",
        code: "YDK-712-95105-404",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Plunger",
        test: "",
        viCode: "",
    }, {
        id: "mV951gB9I6CF1zh4iiTX",
        code: "YDK-735-95248-001",
        definition: "Etiketler",
        explanation: "İngilizce Yan Etiket",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Ops Instr Intl Set",
        test: "true",
        viCode: "122",
    }, {
        id: "mcKbKZ0uLXu3rNQx8Z7P",
        code: "YDK-720-10748-003",
        definition: "Vidalar",
        explanation: "Peripheral Parçası",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Screw M2x6 Pnh Sltd Nylon",
        test: "",
        viCode: "",
    }, {
        id: "nWINxG6nAWBbP4ZGDuyT",
        code: "YDK-712-00631-401",
        definition: "Diğer",
        explanation: "Pole Clamp Siyah Parça",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Tip Shaft Pole Clamp",
        test: "",
        viCode: "",
    }, {
        id: "ngZ3Lb4PphwW85yg35Ol",
        code: "YDK-712-95041-401",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Cap Switch Pwa",
        test: "",
        viCode: "",
    }, {
        id: "o6wLoIcGJ4gJX0RvWcib",
        code: "YDK-712-03402-002",
        definition: "Diğer",
        explanation: "Askı Demiri Plastiği Siyah",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Housing Clutch",
        test: "",
        viCode: "",
    }, {
        id: "pDLrbI4pieCGbcjUwc8f",
        code: "YDK-765-93925-401",
        definition: "Gasket",
        explanation: "Power Gasketi",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Gasket Power Supply",
        test: "",
        viCode: "",
    }, {
        id: "qJ7dJwtZlLFf2C7uyE7f",
        code: "YDK-735-95244-002",
        definition: "Etiketler",
        explanation: "İngilizce Arka Etiket",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Rear Caution Int'l Eng",
        test: "",
        viCode: "",
    }, {
        id: "qezdE3ts9huPUYPhREEQ",
        code: "YDK-765-10922-402",
        definition: "Diğer",
        explanation: "Cpu Yalıtkanı",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Insulator Cpu",
        test: "",
        viCode: "",
    }, {
        id: "qnz66gUk1KUPU2nFZnmY",
        code: "YDK-SUB0000538",
        definition: "Mekanizma",
        explanation: "Basınç Sensörü Strain Gauge",
        model: "Ortak",
        isAvailable: "true",
        name: "Pressure Dedector",
        test: "",
        viCode: "",
    }, {
        id: "qxoRWqHwupGKsXB0rT5g",
        code: "YDK-735-97264-002",
        definition: "Etiketler",
        explanation: "Ses Etiketi Sol+",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Lbl High-low Turkish",
        test: "",
        viCode: "",
    }, {
        id: "r7aaYU0bt7RNu7clUqWp",
        code: "YDK-710-10621-401",
        definition: "Diğer",
        explanation: "Ses Açma Plastiği",
        model: "Plum 360",
        isAvailable: "false",
        name: "Knob Gray 1/8",
        test: "true",
        viCode: "141",
    }, {
        id: "s2tq45CBTTyjQg8CiyhI",
        code: "YDK-712-00714-401",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Bumper Chassis",
        test: "",
        viCode: "",
    }, {
        id: "s4mjnqI7NGfFQJgNyYAe",
        code: "YDK-820-95720-402",
        definition: "Diğer",
        explanation: "Pole Clamp Demiri",
        model: "Plum 360",
        isAvailable: "true",
        name: "Base W/rubber",
        test: "true",
        viCode: "141",
    }, {
        id: "sefKf8gm3VzmCiBfaty4",
        code: "YDK-722-12081-401",
        definition: "Vidalar",
        explanation: "?",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Nut 4-40 Hex Stl Zn Sml S",
        test: "",
        viCode: "",
    }, {
        id: "skN8y1eO0zoCKdOVA5ju",
        code: "YDK-714-98658-401",
        definition: "Diğer",
        explanation: "?",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Clip Regulator Closer",
        test: "",
        viCode: "",
    }, {
        id: "sls0wOPvQ8tbWmT4V4L6",
        code: "YDK-712-95086-009",
        definition: "Kasalar",
        explanation: "Ön Kasa",
        model: "Plum A",
        isAvailable: "true",
        name: "Front Case",
        test: "true",
        viCode: "122",
    }, {
        id: "srAvICV1nvv007b6v1eW",
        code: "YDK-716-95261-401",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçaları",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Vibraiton Isolator",
        test: "",
        viCode: "",
    }, {
        id: "t4peOCmTQItboQLXCOZ5",
        code: "YDK-MEC0000923",
        definition: "Kasalar",
        explanation: "Arka Kasa Rear Case",
        model: "Plum 360",
        isAvailable: "true",
        name: "Housing Back",
        test: "true",
        viCode: "141",
    }, {
        id: "ufxSElIAoQt670jIy6Wb",
        code: "YDK-SUB0000720",
        definition: "Diğer",
        explanation: "Sıvı Kalkanı",
        model: "Plum 360",
        isAvailable: "true",
        name: "Shield",
        test: "true",
        viCode: "122",
    }, {
        id: "um2nMZmPWZ48kqkctiTZ",
        code: "YDK-735-95236-001",
        definition: "Etiketler",
        explanation: "Close Lever Kolu Kapat",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Close Lever W/arrow",
        test: "",
        viCode: "",
    }, {
        id: "uphiwPounmlvdx9gjtUX",
        code: "YDK-725-36531-406",
        definition: "Diğer",
        explanation: "Kablo Bağı",
        model: "Ortak",
        isAvailable: "false",
        name: "Strap Velcro Ac Power Cord",
        test: "true",
        viCode: "141",
    }, {
        id: "v5mrvt9TZScHb4DZNK4B",
        code: "YDK-765-12664-001",
        definition: "Mekanizma",
        explanation: "Yan Kart Koruma Bandı",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Gasket Tape Switch Board",
        test: "",
        viCode: "",
    }, {
        id: "wCzRDepUY0mi7e1dYjWQ",
        code: "YDK-735-98160-401",
        definition: "Etiketler",
        explanation: "Arka Etiket",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Lbl Switch Port",
        test: "",
        viCode: "",
    }, {
        id: "wca9Im8XLaGH0MA3Zhwz",
        code: "YDK-765-94079-401",
        definition: "Diğer",
        explanation: "Yan Kart Koruma Bandı",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Tape Gskt",
        test: "",
        viCode: "",
    }, {
        id: "wxLAyNKHUtBdao9SHgYE",
        code: "YDK-735-98156-401",
        definition: "Etiketler",
        explanation: "Kolu Kapatin Etiketi",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Lbl Door Lever",
        test: "",
        viCode: "",
    }, {
        id: "x0EHb1UkIgiw8CQYubjU",
        code: "YDK-711-16004-005",
        definition: "Diğer",
        explanation: "Peripheral Parçaları Siyah",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Cap F Black Conductive 15-pı",
        test: "",
        viCode: "",
    }, {
        id: "xRRyaSFFLm3nvK0lPuEP",
        code: "YDK-735-95235-001",
        definition: "Etiketler",
        explanation: "Close Lever Kolu Kapat",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Lbl Close Lever",
        test: "",
        viCode: "",
    }, {
        id: "xqW9FJt9wFdB9VNvYIT8",
        code: "YDK-735-10933-001",
        definition: "Etiketler",
        explanation: "Türkçe Üst Etiket",
        model: "Plum A",
        isAvailable: "false",
        name: "Caution Label Turkey",
        test: "true",
        viCode: "122",
    }, {
        id: "y0kmYyLavjgwfw44yoSC",
        code: "YDK-735-98157-401",
        definition: "Etiketler",
        explanation: "Kolu Kapatin Etiketi",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Lbl Close Lever",
        test: "",
        viCode: "",
    }, {
        id: "yfAxLmcsz5Z8SDPid1mS",
        code: "YDK-687-69103-402",
        definition: "Mekanizma",
        explanation: "Üstteki Beyaz Kablo Demiri",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Filter Gm1 Rbn Ca",
        test: "",
        viCode: "",
    }, {
        id: "yuvxWUU3xqSR67wPMBDY",
        code: "YDK-765-94874-403",
        definition: "Diğer",
        explanation: "Siyah",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Insulator Bracket Handle",
        test: "",
        viCode: "",
    }, {
        id: "zI7cy9hDFgkZdphVfORA",
        code: "YDK-717-23016-401",
        definition: "Mekanizma",
        explanation: "Handle Door Yayı",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Spring Skt Extension 1.0 Lss",
        test: "",
        viCode: "",
    }, {
        id: "zMqi5FPgYNIrWwQetlDK",
        code: "YDK-729-95171-402",
        definition: "Mekanizma",
        explanation: "Mekanizma Parçası",
        model: "Ortak",
        isAvailable: "undefined",
        name: "Psa Dampening",
        test: "",
        viCode: "",
    }, {
        id: "zyeJdEYQCYDG4ycEoSwh",
        code: "YDK-720-10323-404",
        definition: "Vidalar",
        explanation: "?",
        model: "Plum 360",
        isAvailable: "undefined",
        name: "Screw 4-40, 3/8, Inhh Sqcn Sl Sem",
        test: "",
        viCode: "",
    }, {
        id: "zygphcR4Ea3FWmXOSWW6",
        code: "YDK-713-90726-002",
        definition: "Diğer",
        explanation: "Askı Demiri Parçası",
        model: "Plum A",
        isAvailable: "undefined",
        name: "Clip Hairpin",
        test: "",
        viCode: "",
    }
]